# Generated by Django 3.0.3 on 2020-03-24 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='キャラクター')),
                ('use', models.IntegerField(blank=True, null=True, verbose_name='使用回数')),
                ('max_dmg', models.IntegerField(default=0, verbose_name='最大ダメージ')),
                ('champion', models.IntegerField(blank=True, null=True, verbose_name='勝利数')),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='名前')),
                ('kind', models.CharField(choices=[('ar', 'ar'), ('smg', 'smg'), ('lmg', 'lmg'), ('sr', 'sr')], max_length=10, verbose_name='武器種')),
                ('bullet', models.CharField(choices=[('ライト', 'ライト'), ('ヘビー', 'ヘビー'), ('エナジー', 'エナジー'), ('ショットガン', 'ショットガン'), ('スナイパー', 'スナイパー')], max_length=10, verbose_name='弾')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dmg', models.IntegerField(default=0, verbose_name='ダメージ')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='順位')),
                ('date', models.DateField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Character')),
                ('member1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member1', to='register.Character')),
                ('member2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member2', to='register.Character')),
                ('mw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_weapon', to='register.Weapon')),
                ('sw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_weapon', to='register.Weapon')),
            ],
        ),
    ]
