# Generated by Django 3.0.3 on 2020-03-24 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='champion',
            field=models.IntegerField(default=0, verbose_name='勝利数'),
        ),
        migrations.AlterField(
            model_name='character',
            name='use',
            field=models.IntegerField(default=0, verbose_name='使用回数'),
        ),
        migrations.AlterField(
            model_name='register',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='member1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member1', to='register.Character'),
        ),
        migrations.AlterField(
            model_name='register',
            name='member2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member2', to='register.Character'),
        ),
        migrations.AlterField(
            model_name='register',
            name='mw',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_weapon', to='register.Weapon'),
        ),
        migrations.AlterField(
            model_name='register',
            name='sw',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_weapon', to='register.Weapon'),
        ),
    ]
